version: "2"

services:
    mongo_db:
        image: mongo
        container_name: mongo_container
        environment:
            - MONGO_INITDB_DATABASE= 'demo'
        ports:
            - '27017:27017'
